"""Generate all 75 golden scenes under the Build.md Part II layout model.

Three arms answer the same question from the same prompts, and this generates either:

    rules    the router's picks from `python -m layoutgen.model.router --golden` - a
             genre, one shape, and whatever options the prompt gave a reason to want
    skill    the same three things chosen by an agent following
             `.cursor/skills/genre-choice/`, one scene per agent, read back through
             `model.handoff`
    answered the same router as `rules`, but re-run on `prompt + author clarifications`
             where an agent stood in for the author and answered the intake's open
             questions before the router picked anything. Configs live at
             `results/routing/answered/<scene>.json` and were written by
             `tools/reclassify_with_answers.py`.
    blob     the prompt uprezzed to a scene description, described as a prose word blob
             against `.cursor/skills/layout-blob/`, then decoupled into a structured
             spec. Specs live at `results/routing/blob/<scene>.json` and were written by
             `tools/run_blob_pipeline.py`. One thing is this arm's own: the body is the
             uprezzed scene prompt rather than the author's raw message. Everything after
             it - the addendum's wording, the order, the wrapper, the style tail - comes
             out of the same `pipeline.spec.build` as every other arm.

They are generated by the same code on purpose. The arms differ in *who chose*, so
anything else that differed would confound the comparison. What the skill arm carries
that the router's cannot is per-scene wording: the router injects an option's document
text on every prompt that picks it, while the skill rewrote each one for the scene in
front of it, and that lands in the same addendum through `edits`.

The addendum is built by the same call the interactive server previews, so what lands
here cannot drift from what the UI showed.

Order decides which of the two images is drawn from text and which is derived from the
other, so whichever runs first is the one that fixes the geometry. It follows the route
the picks force, on every arm: a shape or option carrying `P6` has a topology that must be
valid by construction, which a look-first image cannot guarantee, so the plan is drawn
first and the isometric is dressed from it. A shape with a generator has its blueprint
carved outright. Everything else runs isometric-first.

The `blob` arm states an order of its own and the pipeline does not act on it - see
`pipeline.mapper`. Deriving it identically everywhere is what leaves *who chose the
config* as the difference the comparison is trying to measure.

`raw` and `needs` are not generated here: `results/scenes/` already holds them, and
reusing them keeps the comparison honest and saves 300 calls.

Usage:
    python -m layoutgen.pipeline.golden                  # the rules arm, all 75
    python -m layoutgen.pipeline.golden --arm skill      # the skill arm, all 75
    python -m layoutgen.pipeline.golden --arm skill --limit 4
    python -m layoutgen.pipeline.golden --only 0025,0053
"""

from __future__ import annotations

import argparse
import json
import pathlib
import threading
import time
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, field

from layoutgen import paths
from layoutgen.backends import images
from layoutgen.model import handoff
from layoutgen.model import rules as br
from layoutgen.pipeline import carve as cv
from layoutgen.pipeline import mapper as mp
from layoutgen.pipeline import spec as sp

GOLDEN = paths.PROMPTS
CLASSIFIED = paths.ROUTING / "rules.jsonl"
BLOCKS = paths.ROUTING / "skill"
ANSWERED = paths.ROUTING / "answered"
SPECS = paths.ROUTING / "blob"
E2E = paths.ROUTING / "e2e"
AGENT = paths.ROUTING / "agent_spec"
AGENT_GATEWAY = paths.ROUTING / "agent_spec_gateway"

_lock = threading.Lock()
_done = 0


def _seed(scene: str) -> int:
    """A stable numeric seed for any scene id. Legacy scenes are already numeric;
    upstream scenes carry a `P` prefix that `int(...)` cannot swallow. Stripping
    non-digits keeps the seed deterministic without touching the filenames the
    scene ids are used as."""
    digits = "".join(c for c in scene if c.isdigit())
    return int(digits) if digits else abs(hash(scene)) % (2**31)


def dirs(arm: str) -> tuple:
    """Where one arm's images and run record live."""
    root = paths.SCENES / arm
    return root / "iso", root / "td", root / "plan", paths.RUNS / f"{arm}.jsonl"


@dataclass
class Row:
    scene: str
    title: str
    prompt: str
    genre: str
    preset: str
    shape: str
    shape_label: str
    options: list[str]
    held: list[str]
    extras: list[dict]
    confidence: str
    evidence: str
    route: list[str]
    order: str
    addendum: str
    iso_prompt: str
    td_prompt: str
    #: Only the skill arm fills these: its per-scene rewriting of each option, and the
    #: axis answers a scene with no genre gives instead of naming a shape.
    edits: dict = field(default_factory=dict)
    axes: dict = field(default_factory=dict)
    #: Only the blob arm fills these. The order is stated by the spec rather than
    #: derived from the route, so `why` is the reason it gave for stating it, and
    #: `placements` is what it asked the layout stage to site after segmentation.
    placements: list[dict] = field(default_factory=list)
    scene_prompt: str = ""
    blob: str = ""
    why: str = ""
    iso: str = ""
    td: str = ""
    plan: str = ""
    layout_steps: int = 0
    status: str = "ok"
    error: str = ""
    seconds: float = 0.0
    _spec: dict = field(default_factory=dict, repr=False)


def _clean(text: str) -> str:
    """Turn the CSV import's literal escape sequences back into real whitespace.

    The upstream P-scene prompts landed in the manifest with `\\n` and `\\t` as
    two characters rather than newlines and tabs (the CSV column held them that
    way). Legacy scenes 0001-0075 already carry real newlines, so this is a
    no-op for them.
    """
    return (text.replace("\\r\\n", "\n").replace("\\n", "\n")
                .replace("\\t", "\t"))


def _english() -> dict[str, str]:
    """The English rendering of each prompt an author did not write in English.

    Written by `tools/translate_sources.py`; absent for the ~90% already in English.

    An entry carrying `rejected` is kept on file but not used. Translation can make
    a prompt's violence legible to the image model's content filter when the
    original slipped past it - "matarla" renders, "kill it" is a 400 - and a scene
    with no image at all is a worse outcome than one built from the author's own
    wording. The entry stays so the next reader knows the translation exists and
    why it is not being sent.
    """
    path = paths.ROUTING / "english.jsonl"
    if not path.is_file():
        return {}
    out = {}
    for line in path.open(encoding="utf-8"):
        if not line.strip():
            continue
        r = json.loads(line)
        if (t := (r.get("english") or "").strip()) and not r.get("rejected"):
            out[r["scene"]] = t
    return out


def _manifest() -> dict[str, dict]:
    """Every scene, with the author's message and the body built from it.

    The two are separate because they answer different questions. `source_prompt`
    is what the author wrote and is the record of what was asked for; `body` is what
    the image model is given, which for a prompt written in another language is its
    English translation. Sixty-four of these prompts are in Spanish, Portuguese,
    Arabic, Korean and seven other languages, and the wrapper and addendum around
    them are English either way, so sending the original left the one part of the
    prompt that describes the map in a language the rest of it does not use.

    The translation is literal - see `tools/translate_sources.py` - so the body is
    still the author's content and not a rewrite. The arm that *does* rewrite is
    `blob`, and it uprezzes from the original rather than from this.
    """
    english = _english()
    out = {}
    for line in GOLDEN.open():
        if not line.strip():
            continue
        m = json.loads(line)
        m["source_prompt"] = _clean(m.get("source_prompt", ""))
        m["body"] = english.get(m["scene"]) or m["source_prompt"]
        out[m["scene"]] = m
    return out


def _finish(scene: str, m: dict, genre: str, preset: str, shape_id: str,
            shape_label: str, options: list[str], route: list[str], spec: dict,
            **extra) -> Row:
    """Build one row, and with it the prompts this scene will actually send.

    A P6 route means the topology is the game, so the plan comes first. Where a
    generator exists - mazes and racing circuits - the layout is authored outright
    rather than asked for, which is the whole point of the route.
    """
    kind = cv.layout_kind(genre, shape_id, options)
    order = "layout" if kind else ("p6" if "P6" in route else "std")
    spec = {**spec, "mode": order, "kind": kind or "maze",
            **cv.track_params(genre, shape_id), "stageB": True}
    built = sp.build(spec)
    return Row(
        scene=scene, title=m.get("title", ""), prompt=m["source_prompt"],
        genre=genre, preset=preset, shape=shape_id, shape_label=shape_label,
        options=options, held=built["withheld"], route=route, order=order,
        addendum=built["addendum"], iso_prompt=built["iso"] or "",
        td_prompt=(built["plan"] if order == "p6" else built["topdown"]) or "",
        _spec=spec, **extra)


def rules_rows() -> list[Row]:
    """The router's answer: one constrained LLM call per stage, no conversation."""
    manifest = _manifest()
    out: list[Row] = []
    for r in (json.loads(x) for x in CLASSIFIED.open() if x.strip()):
        m, g = manifest.get(r["scene"]), br.GENRES.get(r["genre"])
        if m is None or g is None:
            continue
        shape = g.shape(r["shape"])
        spec = {"source": m["body"], "genre": r["genre"], "shape": r["shape"],
                "options": r["options"], "edits": {},
                "custom": [e["text"] for e in r.get("extras", [])
                           if e["goes_to"] == "image"]}
        out.append(_finish(
            r["scene"], m, r["genre"], r["preset"], r["shape"],
            shape.label if shape else "", r["options"], r.get("route", []), spec,
            extras=r.get("extras", []), confidence=r["confidence"],
            evidence=r["evidence"]))
    out.sort(key=lambda x: x.scene)
    return out


def skill_rows() -> list[Row]:
    """The skill's answer, one agent per scene, read back through the adapter.

    A block that cannot be adapted is skipped rather than guessed at. Only `P5` - the
    answer that says there is no space to build at all - reaches that today.
    """
    manifest = _manifest()
    out: list[Row] = []
    for path in sorted(BLOCKS.glob("*.json")):
        block, source, scene = handoff.load(path)
        m = manifest.get(scene or path.stem)
        if m is None:
            continue
        h = handoff.adapt(block, source=source or m["body"])
        if not h.ok:
            print(f"  skipped {path.stem}: "
                  + "; ".join(str(p) for p in h.problems if p.kind in handoff.FATAL))
            continue
        g = br.genre(h.genre)
        shape = g.shape(h.spec.get("shape") or "") if g else None
        # A no-genre scene has axes where a genre scene has a shape, so the label the
        # pages show comes from the axes it actually set.
        label = shape.label if shape else ", ".join(h.axes.values()) or "all defaults"
        out.append(_finish(
            path.stem, m, h.genre, h.preset or "none", h.spec.get("shape") or "",
            label, h.options, h.route, h.spec,
            extras=[{"text": t, "goes_to": "image"} for t in h.free_text],
            confidence="", evidence="; ".join(h.notes[:2]),
            edits=dict(h.spec.get("edits") or {}), axes=dict(h.axes)))
    return out


def answered_rows() -> list[Row]:
    """The router's picks after the intake questions were answered.

    An agent read each prompt, answered the open questions the intake skill would
    have asked, and the router ran again on `prompt + answers`. The picks land here
    the same way `rules` does: they are `router.Settings` written out per scene, so
    the pipeline consumes them through the same dict shape.

    The image body deliberately stays the *raw* prompt from the manifest, matching
    the `rules` and `skill` arms; the answered picks already encode what the author
    clarified, so re-injecting the Q&A text would confound the comparison. Raw here
    means unenriched, not untranslated: a prompt written in another language is sent
    as its English body, the same as on every other arm.
    """
    manifest = _manifest()
    out: list[Row] = []
    for path in sorted(ANSWERED.glob("*.json")):
        d = json.loads(path.read_text(encoding="utf-8"))
        scene = d.get("scene") or path.stem
        cfg = d.get("config") or {}
        m = manifest.get(scene)
        if m is None:
            print(f"  skipped {scene}: not in manifest")
            continue
        g = br.GENRES.get(cfg.get("genre", ""))
        if g is None:
            print(f"  skipped {scene}: unknown genre {cfg.get('genre')!r}")
            continue
        shape = g.shape(cfg.get("shape") or "")
        spec = {"source": m["body"], "genre": cfg["genre"],
                "shape": cfg.get("shape") or "", "options": cfg.get("options") or [],
                "edits": {},
                "custom": [e["text"] for e in cfg.get("extras", [])
                           if e.get("goes_to") == "image"]}
        out.append(_finish(
            scene, m, cfg["genre"], cfg.get("preset") or "none",
            cfg.get("shape") or "", shape.label if shape else "",
            cfg.get("options") or [], cfg.get("route") or [], spec,
            extras=cfg.get("extras", []), confidence=cfg.get("confidence", ""),
            evidence=cfg.get("evidence", "")))
    out.sort(key=lambda x: x.scene)
    return out


def blob_rows(specs: pathlib.Path = SPECS) -> list[Row]:
    """The agent-and-skill front half: uprez, then a word blob, then a structured spec.

    The prompt is assembled exactly as every other arm's is - a body with the picked
    options rendered into an addendum after it - so that the arms differ by their picks
    and by nothing else. One thing about it is still this arm's own: the body is the
    uprezzed scene prompt rather than the author's raw message.

    It does not go through `_finish` because the spec's picks arrive shaped differently -
    options as objects rather than ids, and axes where a shape would be - but the order it
    ends up with is the same function of the same picks. `mapper.build` derives it from the
    route, and the blob's own stated order is recorded and not acted on.

    Specs come from `tools/run_blob_pipeline.py`. A scene whose uprez found no space is
    skipped rather than sent: an empty scene prompt would render as a bare style tail.

    `specs` is a directory rather than a constant so the `e2e` arm can reuse this
    verbatim. That arm writes the same record shape from a longer chain - it asks the
    intake questions itself instead of importing them - and reading it through a second
    copy of this function would let the two drift in how a spec becomes a prompt, which
    is the one thing an end-to-end test must share with the arm it is testing.
    """
    manifest = _manifest()
    out: list[Row] = []
    for path in sorted(specs.glob("*.json")):
        d = json.loads(path.read_text(encoding="utf-8"))
        scene = d.get("scene") or path.stem
        m = manifest.get(scene)
        if m is None:
            print(f"  skipped {scene}: not in manifest")
            continue
        if d.get("status") != "ok" or not d.get("spec"):
            print(f"  skipped {scene}: {d.get('status')} at {d.get('stage')}")
            continue
        spec = d["spec"]
        # `br.genre` rather than `GENRES[...]`: No Genre is a real answer here, worth 7% of
        # prompts by the document's own count, and it is absent from that dict.
        g = br.genre(spec.get("genre", ""))
        shape = g.shape(spec.get("shape") or "") if g else None
        built = mp.build(spec)
        out.append(Row(
            scene=scene, title=m.get("title", ""), prompt=m["source_prompt"],
            genre=spec.get("genre", ""), preset=spec.get("preset") or "none",
            shape=spec.get("shape") or "", shape_label=shape.label if shape else "",
            options=[o["id"] for o in spec.get("options") or []],
            held=built["withheld"], placements=built["placements"],
            # No extras: every pick this arm makes has a row in the tables, and the
            # per-scene wording it wrote for them is not sent, so recording it here -
            # where the pages read `extras` as text that was injected - would claim
            # something reached the image that did not. It stays on the spec.
            extras=[],
            confidence="", evidence=built["why"],
            route=built["route"], order=built["order"],
            addendum=built["addendum"],
            iso_prompt=built["iso"] or "",
            td_prompt=(built["plan"] if built["order"] == "p6"
                       else built["topdown"]) or "",
            scene_prompt=d.get("scene_prompt", ""), blob=d.get("blob", ""),
            why=built["why"],
            _spec={**spec, "mode": built["order"], "kind": built["kind"] or "maze",
                   **cv.track_params(spec.get("genre", ""), spec.get("shape") or ""),
                   "stageB": True}))
    out.sort(key=lambda x: x.scene)
    return out


SOURCES = {"rules": rules_rows, "skill": skill_rows, "answered": answered_rows,
           "blob": blob_rows,
           # The same spec-to-prompt path as `blob`, over specs built from nothing but
           # the author's message: `tools/run_e2e_pipeline.py` asks the intake questions
           # and answers them itself rather than importing either.
           "e2e": lambda: blob_rows(E2E),
           # Configs decided by subagents reading the skill files, rather than by one
           # wide gateway call over a compressed menu of them. It reads through
           # `blob_rows` deliberately: `tools/build_agent_arm.py` writes this record
           # shape with the blob arm's own body lifted into it, so the two arms differ
           # in who chose the config and in nothing else.
           "agent": lambda: blob_rows(AGENT),
           # Corrected agent architecture: subagents hand off prose, and the LLM Gateway
           # transcribes that prose into the strict spec consumed here.
           "agent_gateway": lambda: blob_rows(AGENT_GATEWAY)}


def run_one(row: Row, total: int, redo: bool, arm: str) -> Row:
    global _done
    t0 = time.monotonic()
    ISO, TD, PLAN, _ = dirs(arm)
    iso, td = ISO / f"{row.scene}.png", TD / f"{row.scene}.png"
    try:
        if row.order == "layout":
            # Seeded on the scene, so a rerun reproduces the same layout exactly.
            lay = cv.carve({**row._spec, "cells": 13 if row._spec.get("kind") ==
                            "track" else 12, "seed": _seed(row.scene)})
            plan = PLAN / f"{row.scene}.png"
            plan.write_bytes((paths.OUT / lay["layout"]).read_bytes())
            row.plan = plan.name
            row.layout_steps = lay["steps"]
            if redo or not td.is_file():
                images.generate(row.td_prompt, td, [plan])
            if redo or not iso.is_file():
                images.generate(row.iso_prompt, iso, [td])
        elif row.order == "p6":
            # plan first, then dress the isometric from it
            if redo or not td.is_file():
                images.generate(row.td_prompt, td)
            if redo or not iso.is_file():
                images.generate(row.iso_prompt, iso, [td])
        else:
            if redo or not iso.is_file():
                images.generate(row.iso_prompt, iso)
            if redo or not td.is_file():
                images.generate(row.td_prompt, td, [iso])
        row.iso, row.td = iso.name, td.name
    except Exception as exc:
        row.status, row.error = "error", f"{type(exc).__name__}: {exc}"
    row.seconds = round(time.monotonic() - t0, 1)
    with _lock:
        _done += 1
        flag = "" if row.status == "ok" else "  FAILED"
        print(f"  [{_done}/{total}] {row.scene}  {row.genre} :: {row.preset}"
              f"  ({row.order}, {row.seconds}s){flag}", flush=True)
    return row


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--arm", default="rules", choices=sorted(SOURCES),
                    help="which arm's picks to generate from")
    ap.add_argument("--workers", type=int, default=6)
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--only", default="", help="comma-separated scene ids")
    ap.add_argument("--prefix", default="",
                    help="only scenes whose id starts with this - `P` is the 614 "
                         "upstream scenes, which are the ones the answered arm rendered")
    ap.add_argument("--redo", action="store_true", help="regenerate existing images")
    ap.add_argument("--no-checklists", action="store_true",
                    help="skip the eval checklists this would otherwise backfill")
    args = ap.parse_args()

    ISO, TD, PLAN, RUN = dirs(args.arm)
    for d in (ISO, TD, PLAN, paths.RUNS):
        d.mkdir(parents=True, exist_ok=True)

    todo = SOURCES[args.arm]()
    if args.only:
        keep = {s.strip() for s in args.only.split(",")}
        todo = [r for r in todo if r.scene in keep]
    if args.prefix:
        todo = [r for r in todo if r.scene.startswith(args.prefix)]
    if args.limit:
        todo = todo[: args.limit]

    from collections import Counter
    by_order = Counter(r.order for r in todo)
    print(f"generating {len(todo)} {args.arm} scenes  "
          f"({by_order['std']} isometric-first, {by_order['p6']} plan-first, "
          f"{by_order['layout']} authored-layout-first), "
          f"{args.workers} workers", flush=True)
    t0 = time.monotonic()

    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        done = list(pool.map(
            lambda r: run_one(r, len(todo), args.redo, args.arm), todo))

    done.sort(key=lambda r: r.scene)
    # Merge rather than replace: a --only or --limit run must not drop the scenes it
    # was never asked to touch, whose images are still on disk.
    kept = {}
    if RUN.is_file():
        kept = {d["scene"]: d for line in RUN.open() if line.strip()
                for d in [json.loads(line)]}
    for r in done:
        kept[r.scene] = {k: v for k, v in r.__dict__.items()
                         if not k.startswith("_")}
    with RUN.open("w") as fh:
        for scene in sorted(kept):
            fh.write(json.dumps(kept[scene]) + "\n")

    ok = [r for r in done if r.status == "ok"]
    bad = [r for r in done if r.status != "ok"]
    print(f"\n{len(ok)}/{len(done)} ok in {(time.monotonic()-t0)/60:.1f} min")
    print(f"wrote {RUN}")
    for r in bad:
        print(f"  FAILED {r.scene}: {r.error}")

    if not args.no_checklists:
        # Here rather than left to a separate tool: a scene with images and no checklist
        # is invisible to every score, and the arms that predate the extraction each ran
        # for months before anyone noticed they had none. Only the missing are written,
        # so this is free on a re-render.
        from layoutgen.evaluate import checklist
        checklist.ensure(ok, arm=args.arm, workers=args.workers)

    print("\norder:", dict(Counter(r.order for r in done)))
    print("genres:", dict(Counter(r.genre for r in done).most_common(6)))
    inj = [r for r in done if r.addendum]
    print(f"scenes with an injection: {len(inj)}/{len(done)}  "
          f"(mean {sum(len(r.addendum) for r in inj)//max(len(inj),1)} chars)")


if __name__ == "__main__":
    main()
