"""Generate the genre-choice skill files from Build.md.

Build.md is canonical. Two things are produced from it, so neither can drift:

  * .cursor/skills/genre-choice/genres/*.md   verbatim section copies
    python tools/generate_genre_skills.py           # write generated skill files
    python tools/generate_genre_skills.py --check   # exit 1 if stale

--check is the drift guard: run it after editing Build.md Part II.

Copied from mpalleschi/3D-LayoutBuild-Rules, where it was written. One thing
differs here: there is no `pipeline-viewer.html`, so the second half is inert -
this repo's pages are built by `layoutgen.web.pages` from the same document,
and `layoutgen.model.rules` parses it independently. The genre files this
writes are still worth checking: they are a copy, and --check is what says
whether the copy still matches.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from layoutgen.model import rules as br  # noqa: E402

BUILD_MD = REPO / "docs" / "LayoutGen - Build.md"
GENRE_DIR = REPO / ".cursor" / "skills" / "genre-choice" / "genres"
NO_GENRE_MD = GENRE_DIR.parent / "no-genre.md"
VIEWER = REPO / "pipeline-viewer.html"
DATA_START = "/* GENRE-DATA:START — generated by tools/generate_genre_skills.py */"
DATA_END = "/* GENRE-DATA:END */"

# "## **1\. Action**" -> number, title
GENRE_HEADING = re.compile(r"^## \*\*(\d+)\\\. (.+?)\*\*\s*$")
# Any level-1/2 heading or the Themes List ends a genre section.
SECTION_END = re.compile(r"^#{1,2} \*\*")
# The cross-genre options table every genre inherits.
UNIVERSAL_HEADING = re.compile(r"^## \*\*Universal Options\*\*\s*$")
# The no-genre fallback, which is a real outcome on ~7% of prompts.
NO_GENRE_HEADING = re.compile(r"^## \*\*No Genre\*\*\s*$")

BANNER = (
    "<!-- Generated from `docs/LayoutGen - Build.md` Part II by "
    "`tools/generate_genre_skills.py`. Do not edit directly. -->"
)


def slugify(title: str) -> str:
    """'Roleplay & Avatar Sim' -> 'roleplay-avatar-sim'."""
    title = title.split("(")[0]
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower())
    return slug.strip("-")


def parse_genres(text: str) -> list[tuple[int, str, str]]:
    """Return (number, title, body) for each genre section in Part II."""
    lines = text.splitlines()
    starts: list[tuple[int, int, str]] = []
    for i, line in enumerate(lines):
        m = GENRE_HEADING.match(line)
        if m:
            starts.append((i, int(m.group(1)), m.group(2)))

    genres = []
    for idx, (line_no, number, title) in enumerate(starts):
        limit = starts[idx + 1][0] if idx + 1 < len(starts) else len(lines)
        body_lines = []
        for line in lines[line_no + 1 : limit]:
            if SECTION_END.match(line):
                break
            body_lines.append(line)
        # Trim the trailing "---" separator and surrounding blank lines.
        while body_lines and body_lines[-1].strip() in ("", "---"):
            body_lines.pop()
        while body_lines and not body_lines[0].strip():
            body_lines.pop(0)
        genres.append((number, title, "\n".join(body_lines)))
    return genres


def section_body(text: str, heading: re.Pattern[str]) -> str:
    """Body of the standalone (non-numbered) section under `heading`."""
    lines = text.splitlines()
    start = next((i for i, ln in enumerate(lines) if heading.match(ln)), None)
    if start is None:
        return ""
    body: list[str] = []
    for line in lines[start + 1:]:
        if SECTION_END.match(line):
            break
        body.append(line)
    while body and body[-1].strip() in ("", "---"):
        body.pop()
    while body and not body[0].strip():
        body.pop(0)
    return "\n".join(body)


def render(number: int | None, title: str, body: str, universal: str = "") -> str:
    heading = title if number is None else f"{number}. {title}"
    out = f"# {heading}\n\n{BANNER}\n\n{body}\n"
    if universal:
        # Inlined rather than referenced: a genre file is loaded on its own and
        # the skill must not have to go find a second file to know the full menu.
        out += f"\n## Universal Options\n\n{universal}\n"
    return out


# ---------------------------------------------------------------- viewer data

CELL_BOLD = re.compile(r"\*\*(.+?)\*\*")
TYPED_NAME = re.compile(r"^(\w+) \((.+)\)$")
TICKED = re.compile(r"`([^`]+)`")


def split_row(line: str) -> list[str]:
    return [c.strip() for c in line.strip().strip("|").split("|")]


def is_divider(line: str) -> bool:
    return bool(re.match(r"^\|[\s:|-]+\|$", line.strip()))


def table_after(lines: list[str], start: int) -> list[list[str]]:
    """Rows of the first markdown table at or after `start`, header excluded."""
    i = start
    while i < len(lines) and not lines[i].lstrip().startswith("|"):
        i += 1
    if i >= len(lines):
        return []
    i += 1  # header
    if i < len(lines) and is_divider(lines[i]):
        i += 1
    rows = []
    while i < len(lines) and lines[i].lstrip().startswith("|"):
        rows.append(split_row(lines[i]))
        i += 1
    return rows


def parse_name(cell: str) -> tuple[str | None, str]:
    """'**CombatZone (Flat Arena)**' -> ('CombatZone', 'Flat Arena')."""
    m = CELL_BOLD.search(cell)
    text = m.group(1).strip() if m else cell.strip()
    t = TYPED_NAME.match(text)
    return (t.group(1), t.group(2)) if t else (None, text)


def parse_pipeline(cell: str) -> list[str]:
    """'`P6 + P2`' -> ['P6', 'P2']; blank -> []."""
    inner = TICKED.findall(cell)
    if not inner:
        return []
    return [p.strip() for p in inner[0].split("+") if p.strip()]


def find_section(lines: list[str], label: str) -> int:
    for i, line in enumerate(lines):
        if line.lstrip().startswith(f"**{label}"):
            return i
    return -1


def parse_universal_options(universal: str) -> list[dict]:
    lines = universal.splitlines()
    options = []
    for r in table_after(lines, 0):
        if len(r) < 6:
            continue
        otype, oname = parse_name(r[1])
        options.append({"id": r[0].strip("`"), "type": otype, "name": oname,
                        "what": r[2], "core": "●" in r[3],
                        "goesTo": r[4].strip("`") or "image",
                        "pipeline": parse_pipeline(r[5]), "universal": True})
    return options


def parse_genre_data(number: int, title: str, body: str) -> dict:
    lines = body.splitlines()
    tagline = next(
        (ln.strip("* ") for ln in lines if ln.startswith("*") and ln.endswith("*")), ""
    )

    route = []
    for line in lines:
        if line.startswith("**Genre route:"):
            route = parse_pipeline(line)
            break

    shapes = []
    for r in table_after(lines, find_section(lines, "Shape")):
        if len(r) < 4:
            continue
        stype, sname = parse_name(r[1])
        shapes.append({"id": r[0].strip("`"), "type": stype, "name": sname,
                       "what": r[2], "pipeline": parse_pipeline(r[3]) or route})

    options = []
    for r in table_after(lines, find_section(lines, "Options")):
        if len(r) < 6:
            continue
        otype, oname = parse_name(r[1])
        options.append({"id": r[0].strip("`"), "type": otype, "name": oname,
                        "what": r[2], "core": "●" in r[3],
                        "goesTo": r[4].strip("`") or "image",
                        "pipeline": parse_pipeline(r[5])})

    presets = []
    for r in table_after(lines, find_section(lines, "Presets")):
        if len(r) < 4:
            continue
        presets.append({"name": parse_name(r[0])[1], "modelledOn": r[1],
                        "shape": r[2].strip("`"),
                        "options": [o.strip().strip("`") for o in r[3].split(",") if o.strip()]})

    notes_at = find_section(lines, "Genre notes")
    notes = (
        [ln.lstrip("* ").strip() for ln in lines[notes_at:] if ln.startswith("* ")]
        if notes_at >= 0
        else []
    )

    return {"number": number, "title": title, "slug": slugify(title), "tagline": tagline,
            "route": route, "shapes": shapes, "options": options,
            "presets": presets, "notes": notes}


def render_viewer_data(genres: list[dict]) -> str:
    payload = json.dumps(genres, ensure_ascii=False, indent=1)
    return f"{DATA_START}\nconst GENRE_DATA = {payload};\n{DATA_END}"


def merge_universal(genre: dict, universal: list[dict]) -> None:
    """Append universal options, letting a genre's own row win on ID collision."""
    own = {o["id"] for o in genre["options"]}
    genre["options"].extend(o for o in universal if o["id"] not in own)


def validate(genres: list[dict], universal: list[dict] | None = None) -> list[str]:
    problems = []
    universal_ids = {o["id"] for o in (universal or [])}
    shared_shape_ids = set(br.SHAPES)
    for g in genres:
        # Shapes now live in one shared catalogue. A genre section contains only
        # optional wording overrides, so an empty local table is valid.
        shape_ids = shared_shape_ids | {s["id"] for s in g["shapes"]}
        opt_ids = {o["id"] for o in g["options"]} | universal_ids
        if not opt_ids:
            problems.append(f"{g['slug']}: no options parsed")
        if not g["presets"]:
            problems.append(f"{g['slug']}: no presets parsed")
        for p in g["presets"]:
            if p["shape"] not in shape_ids:
                problems.append(f"{g['slug']}: preset '{p['name']}' shape '{p['shape']}' not in shape table")
            for oid in p["options"]:
                if oid not in opt_ids:
                    problems.append(f"{g['slug']}: preset '{p['name']}' option '{oid}' not in options table")
        for o in g["options"]:
            if o["goesTo"] not in ("image", "layout", "both"):
                problems.append(f"{g['slug']}: option '{o['id']}' has bad Goes to '{o['goesTo']}'")
    return problems


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify without writing")
    args = parser.parse_args()

    if not BUILD_MD.exists():
        print(f"error: {BUILD_MD} not found", file=sys.stderr)
        return 2

    build_text = BUILD_MD.read_text(encoding="utf-8")
    genres = parse_genres(build_text)
    if len(genres) != 15:
        print(f"error: expected 15 genres, parsed {len(genres)}", file=sys.stderr)
        return 2

    universal = section_body(build_text, UNIVERSAL_HEADING)
    universal_options = parse_universal_options(universal)
    if not universal_options:
        print("error: Universal Options table parsed empty", file=sys.stderr)
        return 2

    no_genre = section_body(build_text, NO_GENRE_HEADING)
    if not no_genre.strip():
        print("error: No Genre section not found in Build.md", file=sys.stderr)
        return 2

    GENRE_DIR.mkdir(parents=True, exist_ok=True)
    expected: dict[Path, str] = {}
    for number, title, body in genres:
        if not body.strip():
            print(f"error: genre {number} ({title}) parsed empty", file=sys.stderr)
            return 2
        expected[GENRE_DIR / f"{slugify(title)}.md"] = render(number, title, body, universal)
    expected[NO_GENRE_MD] = render(None, "No Genre", no_genre, universal)

    stale: list[str] = []
    for path, content in expected.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        stale.append(path.name)
        if not args.check:
            path.write_text(content, encoding="utf-8")

    for orphan in sorted(GENRE_DIR.glob("*.md")):
        if orphan not in expected:
            stale.append(f"{orphan.name} (orphaned)")
            if not args.check:
                orphan.unlink()

    data = [parse_genre_data(n, t, b) for n, t, b in genres]
    # No Genre is validated on the same rules but kept out of GENRE_DATA — the
    # viewer indexes genres by their Build.md number and this section has none.
    problems = validate(data + [parse_genre_data(0, "No Genre", no_genre)], universal_options)
    for g in data:
        merge_universal(g, universal_options)
    if problems:
        print("error: Build.md Part II failed validation", file=sys.stderr)
        for p in problems:
            print(f"  {p}", file=sys.stderr)
        return 2

    if VIEWER.exists():
        html = VIEWER.read_text(encoding="utf-8")
        if DATA_START not in html or DATA_END not in html:
            print(f"error: {VIEWER.name} is missing the GENRE-DATA markers", file=sys.stderr)
            return 2
        head, rest = html.split(DATA_START, 1)
        _, tail = rest.split(DATA_END, 1)
        updated = head + render_viewer_data(data) + tail
        if updated != html:
            stale.append(f"{VIEWER.name} (GENRE_DATA)")
            if not args.check:
                VIEWER.write_text(updated, encoding="utf-8")

    counts = (len(data), len(br.SHAPES),
              sum(len(g["options"]) for g in data), sum(len(g["presets"]) for g in data))

    if args.check:
        if stale:
            print("stale: " + ", ".join(sorted(stale)), file=sys.stderr)
            print("run: python tools/generate_genre_skills.py", file=sys.stderr)
            return 1
        print(f"OK - {counts[0]} genres, {counts[1]} shared shapes, "
              f"{counts[2]} options, "
              f"{counts[3]} presets all match Build.md")
        return 0

    print(f"updated {len(stale)} target(s); parsed {counts[0]} genres, "
          f"{counts[1]} shared shapes, {counts[2]} options, {counts[3]} presets")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
