"""Generate the genre-choice skill files and the viewer's genre data from Build.md.

Build.md is canonical. Two things are produced from it, so neither can drift:

  * .cursor/skills/genre-choice/genres/*.md   verbatim section copies
  * pipeline-viewer.html GENRE_DATA block     parsed shapes/options/presets

    python tools/generate_genre_skills.py           # write both
    python tools/generate_genre_skills.py --check   # exit 1 if stale

--check is the drift guard: run it after editing Build.md Part II.

The viewer data is injected into the HTML rather than written as a sibling
.json because the viewer is opened over file://, where fetch() is blocked.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BUILD_MD = REPO / "docs" / "LayoutGen - Build.md"
GENRE_DIR = REPO / ".cursor" / "skills" / "genre-choice" / "genres"
NO_GENRE_MD = GENRE_DIR.parent / "no-genre.md"
SHAPES_MD = GENRE_DIR.parent / "shapes.md"
OPTIONS_MD = GENRE_DIR.parent / "options.md"
VIEWER = REPO / "pipeline-viewer.html"
DATA_START = "/* GENRE-DATA:START — generated by tools/generate_genre_skills.py */"
DATA_END = "/* GENRE-DATA:END */"

# "## **1\. Action**" -> number, title
GENRE_HEADING = re.compile(r"^## \*\*(\d+)\\\. (.+?)\*\*\s*$")
# Any level-1/2 heading or the Themes List ends a genre section.
SECTION_END = re.compile(r"^#{1,2} \*\*")
# The cross-genre options table every genre inherits.
UNIVERSAL_HEADING = re.compile(r"^## \*\*Universal Options\*\*\s*$")
# The no-genre fallback, which is a real outcome on ~7% of prompts.
NO_GENRE_HEADING = re.compile(r"^## \*\*No Genre\*\*\s*$")

SHAPE_CATALOG_HEADING = re.compile(r"^## \*\*Shape Catalog\*\*\s*$")
# The neutral one-line concept per shared ID, used as the catalogue's wording.
SHARED_ID_HEADING = re.compile(r"^## \*\*Shared ID registry\*\*\s*$")
# The prose definition of the five axes. Stated twice by necessity, so checked.
AXES_HEADING = re.compile(r"^## \*\*The Five Routing Axes\*\*\s*$")

BANNER = (
    "<!-- Generated from `docs/LayoutGen - Build.md` Part II by "
    "`tools/generate_genre_skills.py`. Do not edit directly. -->"
)


def slugify(title: str) -> str:
    """'Roleplay & Avatar Sim' -> 'roleplay-avatar-sim'."""
    title = title.split("(")[0]
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower())
    return slug.strip("-")


def parse_genres(text: str) -> list[tuple[int, str, str]]:
    """Return (number, title, body) for each genre section in Part II."""
    lines = text.splitlines()
    starts: list[tuple[int, int, str]] = []
    for i, line in enumerate(lines):
        m = GENRE_HEADING.match(line)
        if m:
            starts.append((i, int(m.group(1)), m.group(2)))

    genres = []
    for idx, (line_no, number, title) in enumerate(starts):
        limit = starts[idx + 1][0] if idx + 1 < len(starts) else len(lines)
        body_lines = []
        for line in lines[line_no + 1 : limit]:
            if SECTION_END.match(line):
                break
            body_lines.append(line)
        # Trim the trailing "---" separator and surrounding blank lines.
        while body_lines and body_lines[-1].strip() in ("", "---"):
            body_lines.pop()
        while body_lines and not body_lines[0].strip():
            body_lines.pop(0)
        genres.append((number, title, "\n".join(body_lines)))
    return genres


def section_body(text: str, heading: re.Pattern[str]) -> str:
    """Body of the standalone (non-numbered) section under `heading`."""
    lines = text.splitlines()
    start = next((i for i, line in enumerate(lines) if heading.match(line)), None)
    if start is None:
        return ""
    body: list[str] = []
    for line in lines[start + 1:]:
        if SECTION_END.match(line):
            break
        body.append(line)
    while body and body[-1].strip() in ("", "---"):
        body.pop()
    while body and not body[0].strip():
        body.pop(0)
    return "\n".join(body)


def name_typical_shapes(body: str, catalog: dict[str, dict]) -> str:
    """Put `Type (Flavor Name)` on the Typical shapes shortlist.

    Build.md gives the shortlist as bare IDs, which is right for a document
    whose Shape Catalog is a page away. In a genre file loaded on its own it
    is not: step 6 emits `shape.type` and `shape.name`, and those exist only
    in the catalogue the skill says not to load unless the shortlist misses.
    Nine of twenty pilot lanes read `shapes.md` anyway or emitted nulls.
    """
    line = next(
        (
            candidate
            for candidate in body.splitlines()
            if candidate.startswith("**Typical shapes.")
        ),
        "",
    )
    if not line or not catalog:
        return body

    # A genre may reword a shape it lists; that table is right here in the
    # body, and its wording is the one the offer and the handoff should use.
    wording = {}
    lines = body.splitlines()
    at = wording_section(lines)
    for r in (table_after(lines, at) if at >= 0 else []):
        if len(r) >= 2:
            wtype, wname = parse_name(r[1])
            wording[r[0].strip("`")] = (wtype, wname)

    out = []
    for chunk in line.split("·"):
        tick = TICKED.search(chunk)
        base = catalog.get(tick.group(1)) if tick else None
        if base is None:
            out.append(chunk)
            continue
        wtype, wname = wording.get(tick.group(1),
                                   (base.get("type"), base.get("name")))
        named = f"{wtype} ({wname})" if wtype else str(wname or "")
        # The route matters as much as the name: step 3 asks you to quote what
        # the shape costs, and step 4 routes on it. Without it here the only
        # sources are shapes.md, which step 2 says not to open, or a guess.
        route = " + ".join(f"`{p}`" for p in (base.get("pipeline") or [])) or "`P0`"
        out.append(chunk.replace(tick.group(0),
                                 f"{tick.group(0)} **{named}** {route}", 1))

    note = ("\n\n**The bold name is `Type (Flavor Name)`, and the tag after it "
            "is the shape's route** — between them, everything `shape` and "
            "`pipeline` need at emit. Take both from here rather than loading "
            "`shapes.md`; where this genre rewords a shape, the name above is "
            "already its own.")
    return body.replace(line, "·".join(out) + note, 1)


def render(number: int | None, title: str, body: str, universal: str = "",
           catalog: dict[str, dict] | None = None) -> str:
    if catalog:
        body = name_typical_shapes(body, catalog)
    heading = title if number is None else f"{number}. {title}"
    out = f"# {heading}\n\n{BANNER}\n\n{body}\n"
    if universal:
        # Inlined rather than referenced: a genre file is loaded on its own and
        # the skill must not have to go find a second file to know the full menu.
        out += f"\n## Universal Options\n\n{universal}\n"
    return out


# ---------------------------------------------------------------- viewer data

CELL_BOLD = re.compile(r"\*\*(.+?)\*\*")
TYPED_NAME = re.compile(r"^(\w+) \((.+)\)$")
TICKED = re.compile(r"`([^`]+)`")


def split_row(line: str) -> list[str]:
    return [c.strip() for c in line.strip().strip("|").split("|")]


def is_divider(line: str) -> bool:
    return bool(re.match(r"^\|[\s:|-]+\|$", line.strip()))


def table_after(lines: list[str], start: int) -> list[list[str]]:
    """Rows of the first markdown table at or after `start`, header excluded."""
    i = start
    while i < len(lines) and not lines[i].lstrip().startswith("|"):
        i += 1
    if i >= len(lines):
        return []
    i += 1  # header
    if i < len(lines) and is_divider(lines[i]):
        i += 1
    rows = []
    while i < len(lines) and lines[i].lstrip().startswith("|"):
        rows.append(split_row(lines[i]))
        i += 1
    return rows


def parse_name(cell: str) -> tuple[str | None, str]:
    """'**CombatZone (Flat Arena)**' -> ('CombatZone', 'Flat Arena')."""
    m = CELL_BOLD.search(cell)
    text = m.group(1).strip() if m else cell.strip()
    t = TYPED_NAME.match(text)
    return (t.group(1), t.group(2)) if t else (None, text)


def parse_pipeline(cell: str) -> list[str]:
    """'`P6 + P2`' -> ['P6', 'P2']; blank -> []."""
    inner = TICKED.findall(cell)
    if not inner:
        return []
    return [p.strip() for p in inner[0].split("+") if p.strip()]


def find_section(lines: list[str], label: str) -> int:
    for i, line in enumerate(lines):
        if line.lstrip().startswith(f"**{label}"):
            return i
    return -1


def wording_section(lines: list[str]) -> int:
    """Where a genre's own shape wording starts.

    Not `find_section("Its own wording")`: that wants a bolded label and the
    dedupe pass rewrote the heading to a plain sentence, so the lookup has been
    returning -1 for every genre and every caller has silently been reading
    catalogue wording instead. A pilot lane found the result -- Simulation's
    shortlist saying "Open World" over its own table's "Zone (Shared
    Persistent World)" for the same ID.
    """
    at = find_section(lines, "Its own wording")
    if at >= 0:
        return at
    for i, line in enumerate(lines):
        if "words these its own way" in line:
            return i
    return -1


def parse_universal_options(universal: str) -> list[dict]:
    lines = universal.splitlines()
    options = []
    for r in table_after(lines, 0):
        if len(r) < 6:
            continue
        otype, oname = parse_name(r[1])
        options.append({"id": r[0].strip("`"), "type": otype, "name": oname,
                        "what": r[2], "core": "●" in r[3],
                        "goesTo": r[4].strip("`") or "image",
                        "pipeline": parse_pipeline(r[5]), "universal": True})
    return options


# "`P0 + tiered` for `tiered`, `P2` for `stacked`" -> [("P0 + tiered","tiered"), ("P2","stacked")]
AXIS_PAIR = re.compile(r"`([^`]+)`\s+for\s+`([^`]+)`")


def parse_options_table(lines: list[str], label: str, **extra) -> list[dict]:
    options = []
    for r in table_after(lines, find_section(lines, label)):
        if len(r) < 6:
            continue
        otype, oname = parse_name(r[1])
        options.append({"id": r[0].strip("`"), "type": otype, "name": oname,
                        "what": r[2], "core": "●" in r[3],
                        "goesTo": r[4].strip("`") or "image",
                        "pipeline": parse_pipeline(r[5]), **extra})
    return options


def parse_shared_ids(body: str) -> dict[str, str]:
    """ID -> the registry's neutral one-line concept."""
    out: dict[str, str] = {}
    for r in table_after(body.splitlines(), 0):
        if len(r) >= 2 and r[0].startswith("`"):
            out[r[0].strip("`")] = r[1].strip()
    return out


def build_option_catalog(genres: list[dict], universal: list[dict],
                         concepts: dict[str, str]) -> str:
    """Every option in the system, as one table any genre can reach into.

    Synthesised rather than copied: unlike the Shape Catalog there is no
    single section in Build.md holding these, because a genre's table is
    also where its wording lives. So the catalogue takes the neutral concept
    from the Shared ID registry where there is one, and the sole genre's own
    sentence where an option exists in only one place.
    """
    seen: dict[str, dict] = {}
    owners: dict[str, list[str]] = {}
    routes: dict[str, set[tuple[str, ...]]] = {}
    dests: dict[str, set[str]] = {}
    for section in genres:
        title = section["title"]
        for o in section.get("options", []):
            oid = o["id"]
            seen.setdefault(oid, o)
            owners.setdefault(oid, []).append(title)
            routes.setdefault(oid, set()).add(tuple(o.get("pipeline") or []))
            dests.setdefault(oid, set()).add(o.get("goesTo") or "image")

    universal_ids = {o["id"] for o in universal}

    lines = [
        "Every option in the system, and **every one of them is reachable "
        "from every genre.** A genre's own table is its shortlist and its "
        "wording; this is what it can reach past that. Take any row when the "
        "prompt asks for it, name the genre you took it from, and **write "
        "`text` from the prompt's own words** rather than borrowing the "
        "sentence below.",
        "",
        "**Where a column reads *varies*, the genres genuinely disagree** and "
        "the row cannot settle it for you — follow what the prompt actually "
        "described. A scoring volume is `both` where the goal mouth is a built "
        "thing and `layout` where it is an invisible plane. Everywhere else "
        "`Goes to` and the route come with the row.",
        "",
        "The **Option** column is `Type (Flavor Name)`, as in a genre's own "
        "table. The Type is the Shared Vocabulary term the handoff needs and "
        "is the same in every genre; the flavour name is one genre's wording "
        "and is the part you replace with the prompt's.",
        "",
        "| ID | Option | Concept | Goes to | Pipeline | Worded by |",
        "| :---- | :---- | :---- | :---- | :---- | :---- |",
    ]
    for oid in sorted(seen):
        o = seen[oid]
        concept = concepts.get(oid) or o.get("what") or ""
        concept = " ".join(str(concept).split())
        if len(concept) > 116:
            concept = concept[:113].rstrip() + "…"
        rs = routes[oid]
        if len(rs) > 1:
            route = "*varies*"
        else:
            only = next(iter(rs))
            route = " + ".join(f"`{p}`" for p in only) if only else ""
        who = "**Universal**" if oid in universal_ids else ", ".join(owners[oid])
        if len(who) > 74:
            who = f"{len(owners[oid])} source sections"
        # Without this the handoff cannot be filled: layout_placement.type is
        # the Shared Vocabulary term, and a lane reaching a row it only sees
        # here has nowhere else to read it from.
        typed = f"{o['type']} ({o['name']})" if o.get("type") else str(o.get("name") or "")
        ds = dests[oid]
        dest = "*varies*" if len(ds) > 1 else f"`{next(iter(ds))}`"
        lines.append(f"| `{oid}` | **{typed}** | {concept} | "
                     f"{dest} | {route} | {who} |")
    lines.append("")
    lines.append(f"**{len(seen)} options.** Two thirds of them sit in exactly "
                 "one genre's table, which is why this file exists: the table "
                 "a genre publishes is a shortlist, not a fence.")
    return "\n".join(lines)


def parse_presets_table(lines: list[str]) -> list[dict]:
    presets = []
    for r in table_after(lines, find_section(lines, "Presets")):
        if len(r) < 4:
            continue
        presets.append({"name": parse_name(r[0])[1], "modelledOn": r[1],
                        "shape": r[2].strip("`"),
                        "options": [o.strip().strip("`") for o in r[3].split(",") if o.strip()]})
    return presets


def parse_notes(lines: list[str]) -> list[str]:
    """Note bodies with their inline markdown intact — the viewer renders it.

    Only the list bullet is stripped. `lstrip("* ")` would eat the leading `**`
    of a bolded lead-in too, leaving an unpaired `**` to render literally.
    """
    at = find_section(lines, "Genre notes")
    if at < 0:
        return []
    return [
        re.sub(r"^\*\s+", "", line).strip()
        for line in lines[at:]
        if line.startswith("* ")
    ]


def parse_no_genre(body: str) -> dict:
    """The no-genre fallback as data, so the viewer stops hand-maintaining it.

    Its "shape" table is really five routing axes, and each axis encodes its
    choices in prose rather than columns: the What cell is a `·`-separated list
    of backticked values with the first marked (default), and the Pipeline cell
    either names the value a modifier applies to ("`P3` for `transition` only")
    or gives a bare modifier that applies to every non-default value ("`P4`").
    Both forms are load-bearing, so both are parsed rather than normalised in
    the doc - the prose is what a human reads.
    """
    lines = body.splitlines()

    axes = []
    for r in table_after(lines, find_section(lines, "Shape")):
        if len(r) < 4:
            continue
        choices = []
        for i, chunk in enumerate(r[2].split("·")):
            tick = TICKED.search(chunk)
            if not tick:
                continue
            gloss = TICKED.sub("", chunk, count=1).replace("(default)", "").replace("*", "")
            choices.append({"id": tick.group(1), "gloss": gloss.strip(" ,.;—-"),
                            "default": i == 0})
        pairs = AXIS_PAIR.findall(r[3])
        if pairs:
            routed = {value: [m.strip() for m in mods.split("+")] for mods, value in pairs}
        else:
            routed = {c["id"]: parse_pipeline(r[3]) for c in choices if not c["default"]}
        for c in choices:
            c["pipeline"] = [p for p in routed.get(c["id"], []) if p != "P0"]
        axes.append({"id": r[0].strip("`"), "name": parse_name(r[1])[1], "choices": choices})

    return {"axes": axes,
            "options": parse_options_table(lines, "Options"),
            "presets": parse_presets_table(lines),
            "notes": parse_notes(lines)}


def parse_shape_catalog(body: str) -> dict[str, dict]:
    """The one table that defines every shape, keyed by ID.

    Shapes stopped being private to a genre in Phase 6, so the route lives here
    and only here -- a genre can reword a shape but cannot re-route one.
    """
    catalog = {}
    for r in table_after(body.splitlines(), 0):
        if len(r) < 4:
            continue
        stype, sname = parse_name(r[1])
        sid = r[0].strip("`")
        catalog[sid] = {"id": sid, "type": stype, "name": sname, "what": r[2],
                        "pipeline": parse_pipeline(r[3])}
    return catalog


def parse_genre_data(number: int, title: str, body: str,
                     catalog: dict[str, dict] | None = None) -> dict:
    lines = body.splitlines()
    tagline = next(
        (
            line.strip("* ")
            for line in lines
            if line.startswith("*") and line.endswith("*")
        ),
        "",
    )
    catalog = catalog or {}

    route = []
    for line in lines:
        if line.startswith("**Genre route:"):
            route = parse_pipeline(line)
            break

    # "**Typical shapes.** `a` *(default)* · `b` · `c`" -- presentation only.
    # Every catalogue shape stays reachable; this is the handful worth offering.
    typical, default = [], None
    line = next(
        (candidate for candidate in lines if candidate.startswith("**Typical shapes.")),
        "",
    )
    for chunk in line.split("·"):
        tick = TICKED.search(chunk)
        if not tick:
            continue
        typical.append(tick.group(1))
        if "(default)" in chunk:
            default = tick.group(1)

    wording = {}
    at = wording_section(lines)
    for r in (table_after(lines, at) if at >= 0 else []):
        if len(r) < 3:
            continue
        wtype, wname = parse_name(r[1])
        wording[r[0].strip("`")] = {"type": wtype, "name": wname, "what": r[2]}

    shapes = []
    for sid in typical:
        base = catalog.get(sid)
        if base is None:
            continue
        shapes.append({**base, **wording.get(sid, {}),
                       "pipeline": base["pipeline"] or route})

    return {"number": number, "title": title, "slug": slugify(title), "tagline": tagline,
            "route": route, "shapes": shapes, "typical": typical,
            "default": default or (typical[0] if typical else None),
            "wording": wording,
            "options": parse_options_table(lines, "Options"),
            "presets": parse_presets_table(lines), "notes": parse_notes(lines)}


def option_catalog_data(genres: list[dict],
                        universal: list[dict] | None = None) -> list[dict]:
    """Every non-universal option, tagged with the genres that word it.

    The viewer needs this for the same reason it needs the whole shape
    catalogue: options are reachable from any genre, so showing only the
    fifteen-way split models a menu the skill does not have.

    Excluded by ID rather than by each row's `universal` flag. A genre that
    words a universal option itself produces a row where the flag is false --
    four do, for `building-interior` -- and filtering on the flag would put it
    in the catalogue as well as in the universal block, offering it twice.
    """
    skip = {o["id"] for o in (universal or [])}
    out: dict[str, dict] = {}
    destinations: dict[str, list[str]] = {}
    pipelines: dict[str, list[list[str]]] = {}
    for section in genres:
        for o in section.get("options", []):
            if o["id"] in skip or o.get("universal"):
                continue
            row = out.setdefault(o["id"], {**o, "from": []})
            row["from"].append(section["title"])
            destination = o.get("goesTo") or "image"
            if destination not in destinations.setdefault(o["id"], []):
                destinations[o["id"]].append(destination)
            pipeline = list(o.get("pipeline") or [])
            if pipeline not in pipelines.setdefault(o["id"], []):
                pipelines[o["id"]].append(pipeline)

    rows = []
    for option_id in sorted(out):
        row = out[option_id]
        destination_choices = destinations[option_id]
        pipeline_choices = pipelines[option_id]
        if len(destination_choices) > 1:
            row["goesTo"] = "varies"
            row["goesToChoices"] = destination_choices
        if len(pipeline_choices) > 1:
            # No arbitrary source row may decide a cross-genre route. The viewer
            # asks for the intended interpretation before adding a modifier.
            row["pipeline"] = []
            row["pipelineChoices"] = pipeline_choices
        rows.append(row)
    return rows


def render_viewer_data(genres: list[dict], no_genre: dict,
                       catalog: dict[str, dict] | None = None,
                       universal: list[dict] | None = None) -> str:
    genre_json = json.dumps(genres, ensure_ascii=False, indent=1)
    no_genre_json = json.dumps(no_genre, ensure_ascii=False, indent=1)
    # Shipped whole, not just the shapes each genre lists: the viewer has to be
    # able to offer the rest, or it models a menu the skill does not have.
    catalog_json = json.dumps(list((catalog or {}).values()), ensure_ascii=False, indent=1)
    option_sections = [
        *genres,
        {"title": "No Genre", "options": no_genre.get("options", [])},
    ]
    options_json = json.dumps(
        option_catalog_data(option_sections, universal),
        ensure_ascii=False,
        indent=1,
    )
    return (f"{DATA_START}\nconst GENRE_DATA = {genre_json};\n\n"
            f"const NO_GENRE_DATA = {no_genre_json};\n\n"
            f"const SHAPE_CATALOG = {catalog_json};\n\n"
            f"const OPTION_CATALOG = {options_json};\n{DATA_END}")


def merge_universal(genre: dict, universal: list[dict]) -> None:
    """Append universal options, letting a genre's own row win on ID collision."""
    own = {o["id"] for o in genre["options"]}
    genre["options"].extend(o for o in universal if o["id"] not in own)


def validate(genres: list[dict], universal: list[dict] | None = None,
             catalog: dict[str, dict] | None = None) -> list[str]:
    """Cross-check every reference in Part II, which validates Build.md itself.

    Since Phase 6 a preset's shape is checked against the **catalogue** rather
    than the genre's own list: every shape is reachable from every genre, so
    naming one outside the typical five is legal. What is not legal is naming a
    shape that does not exist.
    """
    problems = []
    universal_ids = {o["id"] for o in (universal or [])}
    catalog = catalog or {}
    for g in genres:
        opt_ids = {o["id"] for o in g["options"]} | universal_ids
        if not g["typical"]:
            problems.append(f"{g['slug']}: no typical shapes parsed")
        if not g.get("default"):
            problems.append(f"{g['slug']}: names no default shape")
        if not opt_ids:
            problems.append(f"{g['slug']}: no options parsed")
        if not g["presets"]:
            problems.append(f"{g['slug']}: no presets parsed")
        for sid in g["typical"]:
            if sid not in catalog:
                problems.append(f"{g['slug']}: typical shape '{sid}' not in Shape Catalog")
        for sid in g["wording"]:
            if sid not in g["typical"]:
                problems.append(f"{g['slug']}: rewords '{sid}', which it does not list as typical")
        for p in g["presets"]:
            if p["shape"] not in catalog:
                problems.append(f"{g['slug']}: preset '{p['name']}' shape '{p['shape']}' not in Shape Catalog")
            for oid in p["options"]:
                if oid not in opt_ids:
                    problems.append(f"{g['slug']}: preset '{p['name']}' option '{oid}' not in options table")
        for o in g["options"]:
            if o["goesTo"] not in ("image", "layout", "both"):
                problems.append(f"{g['slug']}: option '{o['id']}' has bad Goes to '{o['goesTo']}'")
    return problems


def validate_axes_agree(build_text: str, no_genre: dict) -> list[str]:
    """The five axes are stated twice, so make the second copy a checked one.

    `The Five Routing Axes` is the prose definition a reader lands on; the No
    Genre table is what generates `no-genre.md`. Both are hand-written, and the
    pair had already drifted once on naming, so compare ids and defaults.
    """
    rows = table_after(section_body(build_text, AXES_HEADING).splitlines(), 0)
    canon = {}
    for r in rows:
        if len(r) < 4 or not r[0].startswith("`"):
            continue
        canon[r[0].strip("`")] = r[2].strip().strip("`")
    if not canon:
        return ["The Five Routing Axes: table did not parse"]

    problems = []
    if len(canon) != 5:
        problems.append(f"The Five Routing Axes: parsed {len(canon)} axes, expected 5")
    for ax in no_genre["axes"]:
        if ax["id"] not in canon:
            problems.append(f"axes disagree: No Genre has '{ax['id']}', the axes table does not")
            continue
        default = next((c["id"] for c in ax["choices"] if c["default"]), None)
        if default and default != canon[ax["id"]]:
            problems.append(
                f"axes disagree on '{ax['id']}' default: axes table says "
                f"'{canon[ax['id']]}', No Genre says '{default}'")
    for axis_id in canon:
        if axis_id not in {a["id"] for a in no_genre["axes"]}:
            problems.append(f"axes disagree: the axes table has '{axis_id}', No Genre does not")
    return problems


def validate_no_genre_presets(no_genre: dict, universal: list[dict] | None = None) -> list[str]:
    """No Genre answers axes instead of naming a shape, so it cannot use `validate`."""
    problems = []
    axis_ids = {a["id"] for a in no_genre["axes"]}
    opt_ids = {o["id"] for o in no_genre["options"]} | {o["id"] for o in (universal or [])}
    for p in no_genre["presets"]:
        if p["shape"] not in axis_ids:
            problems.append(f"no-genre: preset '{p['name']}' names '{p['shape']}', which is not an axis")
        for oid in p["options"]:
            if oid not in opt_ids:
                problems.append(f"no-genre: preset '{p['name']}' option '{oid}' not in options table")
    return problems


def parse_all(build_text: str) -> tuple[list[dict], dict, dict[str, dict]]:
    """Parsed genres (universal options merged in), the no-genre block, and the
    shape catalogue.

    The single entry point for anything that needs Build.md as data rather than
    as text, so the check tools cannot parse it differently from the generator.
    """
    universal_options = parse_universal_options(section_body(build_text, UNIVERSAL_HEADING))
    catalog = parse_shape_catalog(section_body(build_text, SHAPE_CATALOG_HEADING))
    genres = [parse_genre_data(n, t, b, catalog) for n, t, b in parse_genres(build_text)]
    for g in genres:
        merge_universal(g, universal_options)
    return genres, parse_no_genre(section_body(build_text, NO_GENRE_HEADING)), catalog


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify without writing")
    args = parser.parse_args()

    if not BUILD_MD.exists():
        print(f"error: {BUILD_MD} not found", file=sys.stderr)
        return 2

    build_text = BUILD_MD.read_text(encoding="utf-8")
    genres = parse_genres(build_text)
    if len(genres) != 15:
        print(f"error: expected 15 genres, parsed {len(genres)}", file=sys.stderr)
        return 2

    universal = section_body(build_text, UNIVERSAL_HEADING)
    universal_options = parse_universal_options(universal)
    if not universal_options:
        print("error: Universal Options table parsed empty", file=sys.stderr)
        return 2

    no_genre = section_body(build_text, NO_GENRE_HEADING)
    if not no_genre.strip():
        print("error: No Genre section not found in Build.md", file=sys.stderr)
        return 2

    shape_catalog = parse_shape_catalog(
        section_body(build_text, SHAPE_CATALOG_HEADING))

    GENRE_DIR.mkdir(parents=True, exist_ok=True)
    expected: dict[Path, str] = {}
    for number, title, body in genres:
        if not body.strip():
            print(f"error: genre {number} ({title}) parsed empty", file=sys.stderr)
            return 2
        expected[GENRE_DIR / f"{slugify(title)}.md"] = render(
            number, title, body, universal, shape_catalog)
    expected[NO_GENRE_MD] = render(None, "No Genre", no_genre, universal)
    # Not inlined into the fifteen: unlike Universal Options this is only needed
    # when the genre's typical shapes all miss, so it is one file loaded on
    # demand rather than the same forty rows copied fifteen times.
    expected[SHAPES_MD] = render(None, "Shape Catalog",
                                 section_body(build_text, SHAPE_CATALOG_HEADING))
    # Same reasoning for options: reachable from anywhere, but too long to
    # inline fifteen times, so one file consulted when the genre's own table
    # has no row for what the prompt asked.
    parsed_genres, parsed_no_genre, _ = parse_all(build_text)
    option_sections = [
        *parsed_genres,
        {"title": "No Genre", "options": parsed_no_genre["options"]},
    ]
    expected[OPTIONS_MD] = render(
        None, "Option Catalog",
        build_option_catalog(
            option_sections, universal_options,
            parse_shared_ids(section_body(build_text, SHARED_ID_HEADING))))

    stale: list[str] = []
    for path, content in expected.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        stale.append(path.name)
        if not args.check:
            path.write_text(content, encoding="utf-8")

    for orphan in sorted(GENRE_DIR.glob("*.md")):
        if orphan not in expected:
            stale.append(f"{orphan.name} (orphaned)")
            if not args.check:
                orphan.unlink()

    catalog = parse_shape_catalog(section_body(build_text, SHAPE_CATALOG_HEADING))
    if not catalog:
        print("error: Shape Catalog table parsed empty", file=sys.stderr)
        return 2

    data = [parse_genre_data(n, t, b, catalog) for n, t, b in genres]
    # No Genre is validated on the same rules but kept out of GENRE_DATA — the
    # viewer indexes genres by their Build.md number and this section has none.
    # It ships beside it as NO_GENRE_DATA instead, because the viewer used to
    # hand-maintain its routing axes and they drifted two axes behind.
    problems = validate(data, universal_options, catalog)
    problems += validate_no_genre_presets(parse_no_genre(no_genre), universal_options)
    no_genre_data = parse_no_genre(no_genre)
    if len(no_genre_data["axes"]) != 5:
        problems.append(f"No Genre: expected 5 routing axes, parsed {len(no_genre_data['axes'])}")
    for ax in no_genre_data["axes"]:
        if len(ax["choices"]) < 2:
            problems.append(f"No Genre: axis '{ax['id']}' parsed {len(ax['choices'])} choice(s)")
        if not any(c["default"] for c in ax["choices"]):
            problems.append(f"No Genre: axis '{ax['id']}' has no default choice")
        if not any(c["pipeline"] for c in ax["choices"]):
            problems.append(f"No Genre: axis '{ax['id']}' routes nothing — its Pipeline cell did not parse")
    problems += validate_axes_agree(build_text, no_genre_data)
    for g in data:
        merge_universal(g, universal_options)
    # No Genre inherits them too, and leans on them hardest: a prompt with no
    # genre is usually describing a place, which is what these options describe.
    merge_universal(no_genre_data, universal_options)
    if problems:
        print("error: Build.md Part II failed validation", file=sys.stderr)
        for p in problems:
            print(f"  {p}", file=sys.stderr)
        return 2

    if VIEWER.exists():
        html = VIEWER.read_text(encoding="utf-8")
        if DATA_START not in html or DATA_END not in html:
            print(f"error: {VIEWER.name} is missing the GENRE-DATA markers", file=sys.stderr)
            return 2
        head, rest = html.split(DATA_START, 1)
        _, tail = rest.split(DATA_END, 1)
        updated = head + render_viewer_data(data, no_genre_data, catalog, universal_options) + tail
        if updated != html:
            stale.append(f"{VIEWER.name} (GENRE_DATA)")
            if not args.check:
                VIEWER.write_text(updated, encoding="utf-8")

    counts = (len(data), sum(len(g["shapes"]) for g in data),
              sum(len(g["options"]) for g in data), sum(len(g["presets"]) for g in data))

    if args.check:
        if stale:
            print("stale: " + ", ".join(sorted(stale)), file=sys.stderr)
            print("run: python tools/generate_genre_skills.py", file=sys.stderr)
            return 1
        print(
            f"OK - {counts[0]} genres, {counts[1]} shape shortlist occurrences, "
            f"{counts[2]} option occurrences, {counts[3]} presets all match Build.md"
        )
        return 0

    print(
        f"updated {len(stale)} target(s); parsed {counts[0]} genres, "
        f"{counts[1]} shape shortlist occurrences, {counts[2]} option occurrences, "
        f"{counts[3]} presets"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
